name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Obtain Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn tsc

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - uses: codecov/codecov-action@v1

      - name: Build
        run: yarn build

      - name: Publish
        if: ${{ github.event.release.tag_name }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ./.npmrc
          npm publish pkg
